Implement dataset name changes to tech doc
NOAA-EDAB/tech-doc pull request #124
Opened 2024-11-15 18:51 UTC by BBeltz1

Replace data names that have been changed in ecodata.

Renamed tech doc pages and replaced links to catalog to account for recent data name changes.

Note: `bottom_temp_model_anom` and `thermal_habitat_gridded` do not currently have linked tech doc pages. @jcaracappa1 should the thermal habitat products link to this [Thermal Habitat Projections page](https://noaa-edab.github.io/tech-doc/thermal-habitat-projections.html?q=thermal#thermal-habitat-projections)?  And does the [Bottom Temp High Resolution](https://noaa-edab.github.io/tech-doc/bottom_temp_seasonal_gridded.html?q=bottom%20temp#bottom_temp_seasonal_gridded) page cover the methods for both of your bottom temp products?

This pull requires 1 reviewer to verify that tech doc builds locally.

2024-11-15 18:52 UTC, BBeltz1 commented
This pull also fixes #121

2024-11-18 16:44 UTC, sgaichas requested changes
This does build locally for me;  however a couple things are missing:

Missing reference sections (Doesn't look like this is new in this PR, so not a result of the name changes)
* Bottom temperature in situ
* Cetacean distribution shifts

I think we need a new tech doc page or pages for the thermal habitat indicators. The other page linked under legacy is a separate analysis.

2024-11-18 16:53 UTC, BBeltz1 commented
Thanks Sarah, I'll take a look at the missing references.

I also noticed the missing thermal habitat page(s) but wasn't sure about the legacy page. Thanks for clarifying. @jcaracappa1 I looked through your submissions from last year and didn't see a tech doc page for thermal habitat. Do you remember sending in methods information for the thermal habitat indicators?

2024-11-18 18:41 UTC, andybeet approved these changes
This builds locally for me

2025-02-25 17:19 UTC, closed without merging